[package]
name = "zeta-note"
version = "0.1.0"
authors = ["Artem Pyanykh <artem.pyanykh@gmail.com>"]
edition = "2018"

[dependencies]
clap = "3.0.0-beta.2"
lsp-server = "0.5.0"
lsp-types = "0.88.0"
pulldown-cmark = { version = "0.8", default-features = false }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tracing = "0.1.25"
tracing-subscriber = "0.2.16"
