[package]
name = "zeta-note"
version = "0.1.0"
authors = ["Artem Pyanykh <artem.pyanykh@gmail.com>"]
edition = "2018"

[dependencies]
url = "2.2.0"
tracing-subscriber = "0.2.16"
tracing = "0.1.25"
tokio = { version = "1.2.0", features = ["full"] }
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
pulldown-cmark = { version = "0.8", default-features = false }
once_cell = "1.7.2"
lsp-types = "0.88.0"
lsp-server = "0.5.0"
k9 = "0.10.3"
glob = "0.3.0"
futures = "0.3.13"
clap = "3.0.0-beta.2"
anyhow = "1.0"
