name: Check Commit

on: 
  pull_request:
  push:

jobs:
  check:
    name: Validate on Linux
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup rust toolchian
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
          components: rustfmt, clippy
      
      - name: Run `check`
        uses: actions-rs/cargo@v1
        with:
          command: check

      - name: Run `clippy`
        uses: actions-rs/cargo@v1
        with:
          command: clippy
      
      - name: Run `test`
        uses: actions-rs/cargo@v1
        with:
          command: test